### DISCUSSION TITLE
Using it with pre-commit

### DISCUSSION THREAD

**Discussion by set-soft** [netromdk/vermin#222] [Q&A] [answered]
I'm having problems to use vermin with pre-commit.

I'm using:

```yaml
  - repo: https://github.com/netromdk/vermin
    rev: v1.5.2  # ex: 'e88bda9' or 'v1.3.4'
    hooks:
      - id: vermin
        # specify your target version here, OR in a Vermin config file as usual:
        args: ['-t=3.7-', '--violations']
        # (if your target is specified in a Vermin config, you may omit the 'args' entry entirely)
```

My intention is to detect the use of Python >= 3.8 features.
It usually works, but for very simple files I get:

```
Detecting python files..
Analyzing using 8 processes..
Tips:
- Since '# novm' or '# novermin' weren't used, a speedup can be achieved using: --no-parse-comments
(disable using: --no-tips)

Minimum required versions: 2.7, 3.0
Target versions not met:   3.7-
Note: Number of specified targets (1) doesn't match number of detected minimum versions (2).
```

 I see the docs say:

```
  --target=V | -t=V
        Target version that files must abide by. Can be specified once or twice.
        A '-' can be appended to match target version or smaller, like '-t=3.5-'.
        If not met Vermin will exit with code 1. Note that the amount of target
        versions must match the amount of minimum required versions detected.
        However, if used in conjunction with --violations, and no rules are
        triggered, it will exit with code 0.
```

*Note that the amount of target versions must match the amount of minimum required versions detected.*

But if I use `-t=2.7-  -t=3.7-` I get problems with more complex files where Python 2 isn't supported.

How should I support 1 or 2 versions detection?

BTW: What does *and no rules are triggered* means? I can't see it mentioned in the help.
